apiVersion: batch/v1
kind: Job
metadata:
  name: job-create-topics-parallel-61
  namespace: confluent
  labels:
    app: job-create-topics
spec:
  completions: 50
  parallelism: 25
  completionMode: Indexed
  template:
    spec:
      containers:
      - name: "kafka-perf-create-topics"
        image: "europe-west1-docker.pkg.dev/solutionsarchitect-01/dfederico/kafka-perf-base:latest"
        command: ["create_topics_parallel.sh"]
        env:
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx128M"
        - name: BOOTSTRAP_SERVERS
          value: dfederico-cp61-broker-0:9092
        - name: TOPIC_PREFIX
          value: batch-created6
        - name: TOPIC_COUNT
          value: "50"
        - name: TOPIC_PARTITIONS
          value: "3"
        - name: REPLICATION_FACTOR
          value: "3"

        # envFrom:
        # - configMapRef:
        #     name: createtopics-configmap

        volumeMounts:
        - name: kafka-ca-cert-volume
          mountPath: "/config/certs"
        - name: kafka-connection-properties-volume
          mountPath: "/config/properties"
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 256Mi
      volumes:
      - name: kafka-ca-cert-volume
        secret:
          secretName: kafka-ca-cert
      - name: kafka-connection-properties-volume
        secret:
          secretName: kafka-connection-properties
      restartPolicy: Never
  backoffLimit: 3