apiVersion: v1
kind: Secret
metadata:
  name: kafka-consumer-properties
type: Opaque
data:
  connection.properties: |-
    Ym9vdHN0cmFwLnNlcnZlcnM9ZGZlZGVyaWNvLWNwNjEtYnJva2VyLTA6OTA5MgpzZWN1cml0eS5wcm90b2NvbD1TQVNMX1NTTApzYXNsLmphYXMuY29uZmlnPW9yZy5hcGFjaGUua2Fma2EuY29tbW9uLnNlY3VyaXR5LnBsYWluLlBsYWluTG9naW5Nb2R1bGUgcmVxdWlyZWQgdXNlcm5hbWU9ZGZlZGVyaWNvIHBhc3N3b3JkPWRmZWRlcmljby1zZWNyZXQ7CnNhc2wubWVjaGFuaXNtPVBMQUlOCnNzbC50cnVzdHN0b3JlLnR5cGU9UEVNCnNzbC50cnVzdHN0b3JlLmxvY2F0aW9uPS9jb25maWcvY2VydHMvY2FjZXJ0LnBlbQojIFJlcXVpcmVkIGZvciBjb3JyZWN0bmVzcyBpbiBBcGFjaGUgS2Fma2EgY2xpZW50cyBwcmlvciB0byAyLjYKY2xpZW50LmRucy5sb29rdXA9dXNlX2FsbF9kbnNfaXBzCgo=