apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-perf-configmap
data:
  BOOTSTRAP_SERVERS: dfederico-cp61-broker-0:9092
  TOPIC_NAME: test-1
  GROUP_ID: test-group
  TIMEOUT_MS: "60000"
  MESSAGE_COUNT: "10000000"
